# Generated by Django 3.1.1 on 2020-10-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('artist_title', models.CharField(max_length=100)),
                ('song_title', models.TextField(max_length=1000)),
                ('song_preview', models.URLField()),
                ('album_art', models.URLField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
