# Generated by Django 3.1.1 on 2020-10-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_art',
            new_name='artist_image',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_title',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='convert_time',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_preview',
            new_name='track_preview',
        ),
    ]
