# Generated by Django 3.1.1 on 2020-10-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_auto_20201029_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='convert_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
