# Generated by Django 3.1.1 on 2020-11-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_auto_20201029_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='convert_time',
        ),
    ]
