# Generated by Django 3.1.1 on 2020-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_remove_song_convert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='convert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
