# Generated by Django 3.1.1 on 2020-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_song_convert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='convert_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
