# Generated by Django 3.1.3 on 2020-11-04 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.TextField(max_length=240)),
                ('playlist_members', models.TextField(max_length=1000)),
                ('playlist_id', models.TextField(max_length=20)),
                ('playlist_status', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=7)),
                ('playlist_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
