# Generated by Django 3.1.1 on 2020-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201109_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='owner_access_token',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
