# Generated by Django 3.1.1 on 2020-10-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='actor',
            new_name='Actor',
        ),
    ]
