# Generated by Django 3.1.1 on 2020-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20201013_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_json',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_id',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
