# Generated by Django 3.1.1 on 2020-10-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201023_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.DeleteModel(
            name='Torrent',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
